version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    networks:
      - joyrecord_server_default
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: joyRecord_DB
      MYSQL_USER: joy_user
      MYSQL_PASSWORD: joy1214
    ports:
      - "3306:3306"
    volumes:
      - /mnt/ebs/mysql/mysql/mysql:/var/lib/mysql
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-authentication-plugin=mysql_native_password"

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    networks:
      - joyrecord_server_default
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/joyRecord_DB?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: joy_user
      SPRING_DATASOURCE_PASSWORD: joy1214

volumes:
  mysql-data:
    external: true

networks:
  joyrecord_server_default:
    driver: bridge
