services:
  mysql:
    image:  mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: joyRecord_DB
      MYSQL_USER: joy_dev
      MYSQL_PASSWORD: joyrecord1009
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysqldocker-compose up --build

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://0.0.0.0:3306/joyRecord_DB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000


