services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "0000"
      MYSQL_DATABASE: joyRecord_DB
      MYSQL_USER: joy_dev
      MYSQL_PASSWORD: joyrecord1009
    ports:
      - "3306:3306"
    networks:
      - joyrecord_server_default
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    networks:
      - joyrecord_server_default
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/joyRecord_DB?serverTimezone=UTC&characterEncoding=UTF-8&encrypt=true&trustServerCertificate=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: joy_dev
      SPRING_DATASOURCE_PASSWORD: joyrecord1009

volumes:
  mysql-data:

networks:
  joyrecord_server_default: