version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://192.168.0.22:1433;databaseName=joyRecord
      - SPRING_DATASOURCE_USERNAME=joy_dev
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mssql
