services:
  mysql:
    image:  mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: joyRecord_DB
      MYSQL_USER: joy_dev
      MYSQL_PASSWORD: joyrecord1009
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/joyRecord_DB
      SPRING_DATASOURCE_USERNAME: joy_dev
      SPRING_DATASOURCE_PASSWORD: joyrecord1009
