version: '3.8'

services:
  app:
    image: joy-record-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://192.168.0.22:3306;databaseName=joyrecord_db
      SPRING_DATASOURCE_USERNAME: joy_dev
      SPRING_DATASOURCE_PASSWORD: joyrecord1009

    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: joy_dev
      MYSQL_USER: joy_dev
      MYSQL_PASSWORD: joyrecord1009
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: