services:
  - type: web
    name: spring-boot-app
    env: docker
    repo: https://github.com/pjeasu/joyRecord_server
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://0.0.0.0:3306/joyRecord_DB
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        value: '0000'
    buildCommand: "./gradlew build"
    startCommand: "java -jar build/libs/record-0.0.1-SNAPSHOT.jar"
    healthCheckPath: "/actuator/health"
    plan: starter

  - type: privateService
    name: mysql
    env: docker
    repo: https://github.com/pjeasu/mysql
    branch: oh/mysql_8.0.24
    dockerComposePath: docker-compose.yml
